### ISSUE TITLE
2.0.7 第一次进入的时候，指示器不会选中第一个

### ISSUE THREAD

**Issue by 0924chun** [Bigkoo/Android-ConvenientBanner#238]
并且，作为RecyclerView的headView的时候，从第一个banner滑到最后一个banner或最后一个滑到第一个，均会出现闪一下的症状，不知是否是我使用方式不对，望作者有空看看

**Comment by 0924chun** [comment]
发现设置 app:canLoop="false" 就正常显示指示器，设置 true就不会显示第一个指示器，只有在触摸到banner控件的时候才会显示 demo中的MainActivity也是一样

**Comment by saiwu-bigkoo** [comment]
好的，我写个demo试试

**Comment by saiwu-bigkoo** [comment]
2.0.8已修复，加入header demo
