### ISSUE TITLE
android.view.InflateException: Binary XML file line #138: Binary XML file line #57: Error inflating class com.bigkoo.convenientbanner.ConvenientBanner

### ISSUE THREAD

**Issue by tsdl2018** [Bigkoo/Android-ConvenientBanner#239]
android.view.InflateException: Binary XML file line #138: Binary XML file line #57: Error inflating class com.bigkoo.convenientbanner.ConvenientBanner    2.0.7出错

**Comment by saiwu-bigkoo** [comment]
能贴多点信息吗
