### ISSUE TITLE
import android.support.v7.widget.LinearSnapHelper;     

### ISSUE THREAD

**Issue by tsdl2018** [Bigkoo/Android-ConvenientBanner#240]
import android.support.v7.widget.LinearSnapHelper;  这个找不到

**Comment by saiwu-bigkoo** [comment]
你有没 implementation 'com.android.support:recyclerview-v7:27.0.2'

**Comment by tsdl2018** [comment]
在gradle中已经引入了，运行的时候还是报错

**Comment by tsdl2018** [comment]
# main(2)

java.lang.ClassNotFoundException

Didn't find class "android.support.v7.widget.LinearSnapHelper" on path: DexPathList[[zip file "/data/app/com.sunland.park-KniKzb8Yg1SbFkuxfU3kbA==/base.apk"],nativeLibraryDirectories=[/data/app/com.sunland.park-KniKzb8Yg1SbFkuxfU3kbA==/lib/arm, /data/app/com.sunland.park-KniKzb8Yg1SbFkuxfU3kbA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]

**Comment by tsdl2018** [comment]
我现在只能用回2.0.5版本
