### ISSUE TITLE
希望CBViewHolderCreator可以放一个可以直接new view的接口

### ISSUE THREAD

**Issue by shuaqq** [Bigkoo/Android-ConvenientBanner#242]
像旧版本一样，加载资源的方式固然好，然而banner里有时候只有一个imageview的时候，再去开一个layout感觉有点浪费

**Comment by saiwu-bigkoo** [comment]
能在layout里面配置控件就在layout里，自己new不规范，写个layout也便于以后拓展更复杂内容。
