### ISSUE TITLE
请问能不能关闭滑动

### ISSUE THREAD

**Issue by zhouzl18** [Bigkoo/Android-ConvenientBanner#247]
我现在有个需求是不需要左右滑动，通过按钮来控制左右切换，请问要怎么关闭滑动？

**Comment by saiwu-bigkoo** [comment]
canLoop控制

**Comment by zhouzl18** [comment]
设置canLoop=false后，还是可以左右滑动，只是不能循环。可不可以关闭滑动，但是循环还是可以的？

**Comment by saiwu-bigkoo** [comment]
可以自己setlayoutmanager来控制滑动了

**Comment by VliceZ** [comment]
没那么复杂，startTurning(if(imgUrls.size==1) 1000000 else 5000)  ，不让自动轮播就把turing的时间设置大些，比如我们的情况是只有一张图片的时候不轮播。
