### ISSUE TITLE
怎么加别的翻页效果

### ISSUE THREAD

**Issue by Luopan1** [Bigkoo/Android-ConvenientBanner#248]
比如说加入3D翻页效果？看了源码，似乎没有方法，以前的viewpager的翻页效果对CBLoopViewPager没效果。

**Comment by saiwu-bigkoo** [comment]
实现方式变了，3d效果要用recyclerView的layoutmanager方式实现。目前也未开放对应api，如果你找到recyclerView的3d效果可以通过修改源码进行修改里面的layoutmanager就可以了
