### ISSUE TITLE
轮循一次，会新增一次界面

### ISSUE THREAD

**Issue by yxyaxng** [Bigkoo/Android-ConvenientBanner#250]
我第一张图片开了个定时器，或者打个log，每轮循一次都会新增一个定时器或者新增一条log，可以只留存一条不重复的数据吗，谢谢

**Comment by saiwu-bigkoo** [comment]
这个应该是你使用不当的问题，自带定时器是只有一个，循环都不会new的。而创建视图，比如demo中有7张图片，创建视图创建了6个而已，不是每次创建的。如果你使用2.0.5以前的倒是会创建，新版是不会的。
