### ISSUE TITLE
设置不能手动影响，希望作者能加入进去，代码如下

### ISSUE THREAD

**Issue by yxyaxng** [Bigkoo/Android-ConvenientBanner#251]
因为滑动控制是recyclerview  只要改写LinearLayoutManager

![tim 20180515110631](https://user-images.githubusercontent.com/24906252/40034564-0d0b8978-5830-11e8-90c6-f3c05f8c2061.png)
然后在banner那里写个方法控制一下滚动就好了，谢谢作者

**Comment by saiwu-bigkoo** [comment]
我把setlayoutmanager 的 api 暴露出来了，自己自定义一下就OK

**Comment by justziyang** [comment]
老哥你这个代码不行啊，我设置以后，自动滚动都没有了。。。
