### ISSUE TITLE
使用Glide不能更新网络视图

### ISSUE THREAD

**Issue by XH888** [Bigkoo/Android-ConvenientBanner#252]
holder.pagerBanner.setPages(
                new CBViewHolderCreator() {
                    @Override
                    public BannerImageHolderView createHolder(View itemView) {
                        return new BannerImageHolderView( itemView );
                    }
                    @Override
                    public int getLayoutId() {
                        return R.layout.banner_imgitem;
                    }
                }, item.getBannerBeans());

        class BannerImageHolderView extends Holder<BannerBean> {
            private ImageView imageView;

            public BannerImageHolderView(View itemView ) {
                super(itemView);
            }

            @Override
            protected void initView(View itemView) {
                imageView = itemView.findViewById(R.id.lopageImage);
            }

            @Override
            public void updateUI(BannerBean banner) {
                Glide.with(mContext).load(banner.getCover()).into(imageView);
            }
        }

不知道是不是这样设置、显示没有内容，debug显示有内容传进来

**Comment by saiwu-bigkoo** [comment]
你的glide没配置好吧

**Comment by XH888** [comment]
@saiwu-bigkoo 其他图片都OK，如果这样是正确的话我在检查下。错是没有报，就是没有图片。白屏背景色
