### ISSUE TITLE
请问在Holder中如何获取正确的position?

### ISSUE THREAD

**Issue by zhouzl18** [Bigkoo/Android-ConvenientBanner#253]
现在有个需求，需要把当前的position展示出来，但是我在Holder中直接getAdapterPosition 或 getLayoutPosition都不能获取正确的位置，能不能把正确的position返回？

**Comment by saiwu-bigkoo** [comment]
这个你得自己在源码里面处理了。

**Comment by zhouzl18** [comment]
改源码倒是可以，如果更新了每次都要改源码，你那边方便改下吗
