### ISSUE TITLE
不显示的问题

### ISSUE THREAD

**Issue by Greathfs** [Bigkoo/Android-ConvenientBanner#255]
首先我整个布局是一个 RecyclerView Banner作为头部布局的一部分,我使用了权重后,banner不显示图片了

item_covenientbanner_header.xml demo中的头部布局
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="horizontal">

    <com.bigkoo.convenientbanner.ConvenientBanner
        android:id="@+id/convenientBanner"
        android:layout_width="0dp"
        android:layout_weight="1"
        android:layout_height="520dp"
        app:autoTurningTime="3000"
        app:canLoop="true"/>

    <RelativeLayout
        android:layout_width="0dp"
        android:layout_weight="2"
        android:layout_height="match_parent"/>

</LinearLayout>
```

其他我都没改,之后运行下代码 点击跳转到HeadActivity 上面的Banner图不显示了

**Comment by Greathfs** [comment]
这个挺着急 麻烦作者帮忙解决下啊

**Comment by saiwu-bigkoo** [comment]
你这个权重有什么意义吗？完全就没必要，直接match_parent

**Comment by Greathfs** [comment]
我的header不只有banner 右侧还有别的控件

**Comment by saiwu-bigkoo** [comment]
我在demo中，item_covenientbanner_header 里面改为
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="horizontal" android:layout_width="match_parent"
    android:layout_height="match_parent">
    <com.bigkoo.convenientbanner.ConvenientBanner
        android:id="@+id/convenientBanner"
        android:layout_weight="1"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        app:canLoop="true"
        app:autoTurningTime="3000"/>

    <TextView
        android:text="hhhh"
        android:layout_width="50dp"
        android:layout_height="50dp" />
</LinearLayout>`
完全没问题，右侧有TextView出来，左侧也没有空白的问题出现。

**Comment by Greathfs** [comment]
嗯 但是权重一般都是设置width或者height是0dp 设置match_parent的话可能会出现比例的问题 既然match_parent没问题 那我自己调下权重比例就好了
