### ISSUE TITLE
使用了notifyDataSetChanged方法会快速刷新好几条

### ISSUE THREAD

**Issue by xieyang94** [Bigkoo/Android-ConvenientBanner#262]
本来是一条也没有的，然后请求网络获取到了两条数据（耗时好几秒），然后使用notifyDataSetChanged更新数据，就会快速的刷新过好多条（数了一下，大概快速刷新了6条），不懂为什么

**Comment by saiwu-bigkoo** [comment]
会不会是你的机制问题，反复调用了几次

**Comment by saiwu-bigkoo** [comment]
这个是我notify的时候没把item置为0，所以它从0滚到上一次的位置去了，最新版2.1.3已解决
