### ISSUE TITLE
是不是要更新一下使用文档了？Holder类已经不是接口了？

### ISSUE THREAD

**Issue by cyixlq** [Bigkoo/Android-ConvenientBanner#263]
今天自定义Holder的时候发现按文档上用实现接口方式报错了，进去源代码看的话发现Holder是抽象类了？使用方法具体是什么样的呢？还望更新使用说明！

**Comment by saiwu-bigkoo** [comment]
好的，已更新，demo有更详细的用法你可以看看

**Comment by EmccK** [comment]
还是没更新啊，只是注释掉了

**Comment by SMAXLYB** [comment]
看demo看的我一脸懵逼
