### ISSUE TITLE
2.14解析xml报错

### ISSUE THREAD

**Issue by wangsfine** [Bigkoo/Android-ConvenientBanner#265]
2.14解析xml报错 Caused by: java.lang.NoClassDefFoundError: android.support.v7.widget.PagerSnapHelper，依赖里面没有这个工具类

**Comment by saiwu-bigkoo** [comment]
你的gradle implementation 'com.android.support:recyclerview-v7:27.0.2'

**Comment by wangsfine** [comment]
thanks,it worked powerful!
