### ISSUE TITLE
RecyclerView 多布局嵌套使用，不能自动轮播什么鬼

### ISSUE THREAD

**Issue by MyChanges** [Bigkoo/Android-ConvenientBanner#268]
RecyclerView 多布局嵌套使用，不能自动轮播什么鬼

**Comment by MyChanges** [comment]
<com.bigkoo.convenientbanner.ConvenientBanner
        android:id="@+id/re_banner"
        android:layout_width="match_parent"
        android:layout_height="130dip"
        android:gravity="center"
        app:canLoop="true"
        app:autoTurningTime="3000"
     />

**Comment by saiwu-bigkoo** [comment]
你得主动startTurning

**Comment by MyChanges** [comment]
没错，是这样
