### ISSUE TITLE
多次调用startTurning问题

### ISSUE THREAD

**Issue by JuneJun** [Bigkoo/Android-ConvenientBanner#275]
多次调用startTurning ，然后再调用stopTurning，再用手指滑动切换页面，就会发生自动滚动的情况，主要代码如下：
 banner.startTurning();
 banner.startTurning();
 banner.stopTurning();
感觉像是这个方法removeCallbacks没有移除掉所以消息

**Comment by JuneJun** [comment]
应该是这个字段canTurn在stopTurning方法了没有改为false

**Comment by saiwu-bigkoo** [comment]
是的，因为stop不代表不能再turning，这个stop初衷是跳转其他页面的时候，停止翻页，而不是控制不能翻页。你要不能翻页要调用 canTurn为false

**Comment by JuneJun** [comment]
private boolean canTurn ；canTurn为私有的，调用不了

**Comment by saiwu-bigkoo** [comment]
这个确实没考虑到你这种情况，你import源码自己改一下
