### ISSUE TITLE
Banner notifyDataSetChanged 更新的问题

### ISSUE THREAD

**Issue by tzizi5566** [Bigkoo/Android-ConvenientBanner#278]
作者你好，我现在的Banner里每个页面都有点赞功能，当我点赞后调用notifyDataSetChanged Banner会跳回到第一页去，想问下有什么方法可以局部刷新呢？

**Comment by saiwu-bigkoo** [comment]
里面实现是recyclerView的，我并没开放recyclerView的api，你得自己下源码改了。
