### ISSUE TITLE
第一个Item滑动到前一个item时闪一下

### ISSUE THREAD

**Issue by KevinXiao7** [Bigkoo/Android-ConvenientBanner#309]
第一个Item滑动到前一个item时闪一下，在最后一个item滑到第一个item的时候会闪烁一下

**Comment by KevinXiao7** [comment]
> 第一个Item滑动到前一个item时闪一下，在最后一个item滑到第一个item的时候会闪烁一下

**Comment by Chu-Dream** [comment]
我也遇到了，怎么解决的？
